services:
  server:
    image: szurubooru/server:latest
    depends_on:
      - sql
    restart: unless-stopped
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER: szuru
      POSTGRES_PASSWORD: c58283e2d441060a36c0d92d7d90a328
      THREADS: "4"
      CONFIG_YAML_B64: bmFtZTog44OS44Kr44Oe44O8Qm9vcnUKZG9tYWluOiBodHRwczovL2hpa2Fib29ydS5oaWthbWVyLmY1LnNpCnNlY3JldDogZjExNWQ0ZjdhMjIxZWNkYjNmNzcwNzlkNDVlZTg4N2M4MDE2Y2VhMjNhNzMxYWJmYzIxZjFhZGZhN2M4MjQ3MQplbmFibGVfc2FmZXR5OiAibm8iCmRlZmF1bHRfcmFuazogcmVndWxhcgp0YWdfbmFtZV9yZWdleDogXlxTKyQKcGFzc3dvcmRfcmVnZXg6ICdeLns1LH0kJwp1c2VyX25hbWVfcmVnZXg6ICdeW2EtekEtWjAtOV8tXXsxLDMyfSQnCnRodW1ibmFpbHM6CiAgYXZhdGFyX3dpZHRoOiAzMDAKICBhdmF0YXJfaGVpZ2h0OiAzMDAKICBwb3N0X3dpZHRoOiAzMDAKICBwb3N0X2hlaWdodDogMzAwCnByaXZpbGVnZXM6CiAgICAndXNlcnM6Y3JlYXRlOnNlbGYnOiAgICAgICAgICAgIGFub255bW91cwogICAgJ3VzZXJzOmxpc3QnOiAgICAgICAgICAgICAgICAgICBhbm9ueW1vdXMKICAgICd1c2Vyczp2aWV3JzogICAgICAgICAgICAgICAgICAgYW5vbnltb3VzCiAgICAndXNlcnM6ZWRpdDpzZWxmOm5hbWUnOiAgICAgICAgIGFub255bW91cwogICAgJ3VzZXJzOmVkaXQ6c2VsZjpwYXNzJzogICAgICAgICBhbm9ueW1vdXMKICAgICd1c2VyczplZGl0OnNlbGY6ZW1haWwnOiAgICAgICAgYW5vbnltb3VzCiAgICAndXNlcnM6ZGVsZXRlOnNlbGYnOiAgICAgICAgICAgIGFub255bW91cwogICAgJ3VzZXJfdG9rZW5zOmxpc3Q6c2VsZic6ICAgICAgICBhbm9ueW1vdXMKICAgICd1c2VyX3Rva2VuczpjcmVhdGU6c2VsZic6ICAgICAgYW5vbnltb3VzCiAgICAndXNlcl90b2tlbnM6ZWRpdDpzZWxmJzogICAgICAgIGFub255bW91cwogICAgJ3VzZXJfdG9rZW5zOmRlbGV0ZTpzZWxmJzogICAgICBhbm9ueW1vdXMKICAgICdwb3N0czpjcmVhdGU6YW5vbnltb3VzJzogICAgICAgYW5vbnltb3VzCiAgICAncG9zdHM6Y3JlYXRlOmlkZW50aWZpZWQnOiAgICAgIGFub255bW91cwogICAgJ3Bvc3RzOmxpc3QnOiAgICAgICAgICAgICAgICAgICBhbm9ueW1vdXMKICAgICdwb3N0czp2aWV3JzogICAgICAgICAgICAgICAgICAgYW5vbnltb3VzCiAgICAncG9zdHM6dmlldzpmZWF0dXJlZCc6ICAgICAgICAgIGFub255bW91cwogICAgJ3Bvc3RzOmVkaXQ6dGFncyc6ICAgICAgICAgICAgICBhbm9ueW1vdXMKICAgICdwb3N0czplZGl0OnNhZmV0eSc6ICAgICAgICAgICAgYW5vbnltb3VzCiAgICAncG9zdHM6ZWRpdDpzb3VyY2UnOiAgICAgICAgICAgIGFub255bW91cwogICAgJ3Bvc3RzOmVkaXQ6cmVsYXRpb25zJzogICAgICAgICBhbm9ueW1vdXMKICAgICdwb3N0czplZGl0Om5vdGVzJzogICAgICAgICAgICAgYW5vbnltb3VzCiAgICAncG9zdHM6c2NvcmUnOiAgICAgICAgICAgICAgICAgIGFub255bW91cwogICAgJ3Bvc3RzOmZhdm9yaXRlJzogICAgICAgICAgICAgICBhbm9ueW1vdXMKICAgICdwb3N0czpkZWxldGUnOiAgICAgICAgICAgICAgICAgcmVndWxhcgogICAgJ3RhZ3M6dmlldyc6ICAgICAgICAgICAgICAgICAgICBhbm9ueW1vdXMKICAgICd0YWdzOmxpc3QnOiAgICAgICAgICAgICAgICAgICAgYW5vbnltb3VzCiAgICAndGFnczpjcmVhdGUnOiAgICAgICAgICAgICAgICAgIGFub255bW91cwogICAgJ3RhZ3M6ZWRpdDpuYW1lcyc6ICAgICAgICAgICAgICBhbm9ueW1vdXMKICAgICd0YWdzOmVkaXQ6ZGVzY3JpcHRpb24nOiAgICAgICAgYW5vbnltb3VzCiAgICAndGFnczpkZWxldGUnOiAgICAgICAgICAgICAgICAgIHJlZ3VsYXIKICAgICdjb21tZW50czpjcmVhdGUnOiAgICAgICAgICAgICAgYW5vbnltb3VzCiAgICAnY29tbWVudHM6ZWRpdDpvd24nOiAgICAgICAgICAgIGFub255bW91cwogICAgJ2NvbW1lbnRzOmRlbGV0ZTpvd24nOiAgICAgICAgICBhbm9ueW1vdXMKICAgICdjb21tZW50czpsaXN0JzogICAgICAgICAgICAgICAgYW5vbnltb3VzCiAgICAnY29tbWVudHM6c2NvcmUnOiAgICAgICAgICAgICAgIGFub255bW91cwogICAgJ3Bvb2xzOmNyZWF0ZSc6ICAgICAgICAgICAgICAgICBhbm9ueW1vdXMKICAgICdwb29sczp2aWV3JzogICAgICAgICAgICAgICAgICAgYW5vbnltb3VzCiAgICAncG9vbHM6ZWRpdDpwb3N0cyc6ICAgICAgICAgICAgIGFub255bW91cwogICAgJ3Bvb2xzOmRlbGV0ZSc6ICAgICAgICAgICAgICAgICByZWd1bGFyCiAgICAndXBsb2FkczpjcmVhdGUnOiAgICAgICAgICAgICAgIGFub255bW91cwo=
    entrypoint: ["/usr/bin/dumb-init", "/bin/sh", "-c"]
    command: ["echo \"$CONFIG_YAML_B64\" | base64 -d > /opt/app/config.yaml && exec /opt/app/docker-start.sh"]
    volumes:
      - szuru_data:/data

  client:
    image: szurubooru/client:latest
    depends_on:
      - server
    restart: unless-stopped
    environment:
      BACKEND_HOST: server
      BASE_URL: /
    volumes:
      - szuru_data:/data:ro

  sql:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: szuru
      POSTGRES_PASSWORD: c58283e2d441060a36c0d92d7d90a328
    volumes:
      - szuru_sql:/var/lib/postgresql/data

volumes:
  szuru_data:
  szuru_sql:

# force redeploy 1782876260
