services:
  server:
    image: szurubooru/server:latest
    user: root
    depends_on:
      - sql
    restart: unless-stopped
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER: szuru
      POSTGRES_PASSWORD: c58283e2d441060a36c0d92d7d90a328
      THREADS: "4"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "cp /opt/app/config.yaml.dist /opt/app/config.yaml.dist.bak && cat /opt/app/config.yaml && exec /opt/app/docker-start.sh"
    volumes:
      - szuru_data:/data
      - ./server/config.yaml:/opt/app/config.yaml

  client:
    image: szurubooru/client:latest
    depends_on:
      - server
    restart: unless-stopped
    environment:
      BACKEND_HOST: server
      BASE_URL: /
    volumes:
      - szuru_data:/data:ro

  sql:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: szuru
      POSTGRES_PASSWORD: c58283e2d441060a36c0d92d7d90a328
    volumes:
      - szuru_sql:/var/lib/postgresql/data

volumes:
  szuru_data:
  szuru_sql:

# force redeploy 1782876263
