name: ヒカマーBooru
domain: https://hikabooru.hikamer.f5.si
secret: f115d4f7a221ecdb3f77079d45ee887c8016cea23a731abfc21f1adfa7c82471
enable_safety: "no"
default_rank: regular
tag_name_regex: ^\S+$
password_regex: '^.{5,}$'
user_name_regex: '^[a-zA-Z0-9_-]{1,32}$'
thumbnails:
  avatar_width: 300
  avatar_height: 300
  post_width: 300
  post_height: 300
privileges:
    'users:create:self':            anonymous
    'users:list':                   anonymous
    'users:view':                   anonymous
    'users:edit:self:name':         anonymous
    'users:edit:self:pass':         anonymous
    'users:edit:self:email':        anonymous
    'users:delete:self':            anonymous
    'user_tokens:list:self':        anonymous
    'user_tokens:create:self':      anonymous
    'user_tokens:edit:self':        anonymous
    'user_tokens:delete:self':      anonymous
    'posts:create:anonymous':       anonymous
    'posts:create:identified':      anonymous
    'posts:list':                   anonymous
    'posts:view':                   anonymous
    'posts:view:featured':          anonymous
    'posts:edit:tags':              anonymous
    'posts:edit:safety':            anonymous
    'posts:edit:source':            anonymous
    'posts:edit:relations':         anonymous
    'posts:edit:notes':             anonymous
    'posts:score':                  anonymous
    'posts:favorite':               anonymous
    'posts:delete':                 regular
    'tags:view':                    anonymous
    'tags:list':                    anonymous
    'tags:create':                  anonymous
    'tags:edit:names':              anonymous
    'tags:edit:description':        anonymous
    'tags:delete':                  regular
    'comments:create':              anonymous
    'comments:edit:own':            anonymous
    'comments:delete:own':          anonymous
    'comments:list':                anonymous
    'comments:score':               anonymous
    'pools:create':                 anonymous
    'pools:view':                   anonymous
    'pools:edit:posts':             anonymous
    'pools:delete':                 regular
    'uploads:create':               anonymous
